export const stackedData = [
  { orderStage: "Order Authorized", key: "Sep 1", value: 100.9 },
  { orderStage: "Order Authorized", key: "Sep 2", value: 28.8 },
  { orderStage: "Order Authorized", key: "Sep 4", value: 81.4 },
  { orderStage: "Order Authorized", key: "Sep 3", value: 39.3 },
  { orderStage: "Order Authorized", key: "Sep 5", value: 47 },
  { orderStage: "Order Authorized", key: "Sep 6", value: 20.3 },
  { orderStage: "Order Authorized", key: "Sep 7", value: 24 },
  { orderStage: "Order Authorized", key: "Sep 8", value: 100.9 },
  { orderStage: "Order Authorized", key: "Sep 9", value: 28.8 },
  { orderStage: "Order Authorized", key: "Sep 10", value: 81.4 },
  { orderStage: "Order Authorized", key: "Sep 11", value: 39.3 },
  { orderStage: "Order Authorized", key: "Sep 12", value: 47 },
  { orderStage: "Order Authorized", key: "Sep 13", value: 20.3 },
  { orderStage: "Order Authorized", key: "Sep 14", value: 24 },
  { orderStage: "Order Authorized", key: "Sep 15", value: 100.9 },
  { orderStage: "Order Authorized", key: "Sep 16", value: 28.8 },
  { orderStage: "Order Authorized", key: "Sep 17", value: 81.4 },
  { orderStage: "Order Authorized", key: "Sep 18", value: 39.3 },
  { orderStage: "Order Authorized", key: "Sep 19", value: 47 },
  { orderStage: "Order Authorized", key: "Sep 20", value: 20.3 },
  { orderStage: "Order Authorized", key: "Sep 21", value: 24 },
  { orderStage: "Order Pending", key: "Sep 1", value: 35.9 },
  { orderStage: "Order Pending", key: "Sep 2", value: 4.8 },
  { orderStage: "Order Pending", key: "Sep 3", value: 56.3 },
  { orderStage: "Order Pending", key: "Sep 4", value: 70.4 },
  { orderStage: "Order Pending", key: "Sep 5", value: 67 },
  { orderStage: "Order Pending", key: "Sep 6", value: 54.3 },
  { orderStage: "Order Pending", key: "Sep 7", value: 34 },
  { orderStage: "Order Dispatched", key: "Sep 1", value: 45 },
  { orderStage: "Order Dispatched", key: "Sep 2", value: 33 },
  { orderStage: "Order Dispatched", key: "Sep 3", value: 67 },
  { orderStage: "Order Dispatched", key: "Sep 4", value: 21.4 },
  { orderStage: "Order Dispatched", key: "Sep 5", value: 34 },
  { orderStage: "Order Dispatched", key: "Sep 6", value: 66.3 },
  { orderStage: "Order Dispatched", key: "Sep 7", value: 65 },
  { orderStage: "Order Delivered", key: "Sep 1", value: 56 },
  { orderStage: "Order Delivered", key: "Sep 2", value: 76 },
  { orderStage: "Order Delivered", key: "Sep 3", value: 87 },
  { orderStage: "Order Delivered", key: "Sep 4", value: 44.4 },
  { orderStage: "Order Delivered", key: "Sep 5", value: 33 },
  { orderStage: "Order Delivered", key: "Sep 6", value: 22.3 },
  { orderStage: "Order Delivered", key: "Sep 7", value: 45 },
];

export const lineData = [
  {
    date: 'Sep 1',
    duration: 'This week',
    orders: 8,
  },
  {
    date: 'Sep 1',
    duration: 'Previous week',
    orders: 3.9,
  },
  {
    date: 'Sep 2',
    duration: 'Previous week',
    orders: 12,
  },
  {
    date: 'Sep 2',
    duration: 'This week',
    orders: 10,
  },
  {
    date: 'Sep 3',
    duration: 'Previous week',
    orders: 7,
  },
  {
    date: 'Sep 3',
    duration: 'This week',
    orders: 8,
  },
  {
    date: 'Sep 4',
    duration: 'This week',
    orders: 14.5,
  },
  {
    date: 'Sep 4',
    duration: 'Previous week',
    orders: 8.5,
  },
  {
    date: 'Sep 5',
    duration: 'This week',
    orders: 12,
  },
  {
    date: 'Sep 5',
    duration: 'Previous week',
    orders: 14,
  },
  {
    date: 'Sep 6',
    duration: 'This week',
    orders: 20,
  },
  {
    date: 'Sep 6',
    duration: 'Previous week',
    orders: 10,
  },
  {
    date: 'Sep 7',
    duration: 'This week',
    orders: 25.2,
  },
  {
    date: 'Sep 7',
    duration: 'Previous week',
    orders: 17,
  },
];
